### ISSUE TITLE
Add destroy method for cleaning up

### ISSUE THREAD

**Issue by Worie** [mladenilic/threesixty#1]
Hi, thanks for the working, simple lib!

Would you consider adding a destroy method to the three sixty instance, that would clean up every event-listener and perhaps delete the slider?

**Comment by mladenilic** [comment]
Hey Worie, thanks for the feedback. :)
 
Sure, makes sense to have a way to clean up the events. I'll look into implementing a destroy method.

**Comment by Worie** [comment]
Awesome, thanks for the quick reply! :)

**Comment by mladenilic** [comment]
Hi @Worie, just letting you know that the destroy method has been implemented.

It does the following: 
- Stop auto-rotate
- Clean up events
- Reset container div back to it's original state

Sorry it took me a while to implement it and thank you for the contribution! 🎉

**Comment by Worie** [comment]
Awesome! Thank you really much ;)
