### ISSUE TITLE
Error getting image array

### ISSUE THREAD

**Issue by jonalxh** [mladenilic/threesixty#11]
Hi.

I'm trying to make the plugin works with an image array as said in documentation, It works if I just have one image path, with more than one the request crashes and answers an 404 not found, it is because of threesixty concatenates the array indexes and tries to get the images as one:

```
const threesixty = new ThreeSixty(document.getElementById('threesixty'), {
            image: [
                'static/img/rotation/1.jpeg',
                'static/img/rotation/2.jpeg'
           ]
});
```

The resulting request is the following:

`http://localhost:5003/static/img/rotation/1.jpeg,static/img/rotation/2.jpeg`

Take a look to the comma present in the URL. Due this the images are not found. 

Is there a way to avoid paths concatenation and get the files one by one?

Thanks a lot

**Comment by mladenilic** [comment]
Hi @jonalxh,

Thanks for taking time to open the issue. Can you please tell me how are you loading threesixty.js? Are you using npm package or jsdelivr cdn? It will help me recreate the issue.

Here's a working sample https://codepen.io/mladenilic/pen/bXLxQo. (I just cropped the images by hand, so the rotation is choppy, but other than that works as expected.)

If you are using npm package or have a local copy, can you try and update it?

**Comment by jonalxh** [comment]
Hi @mladenilic.

You're totally right, I've tried with your code and it works, the problem was I had been using a local copy of the minified JS file and it was incomplete. Take a look, [this is](https://github.com/mladenilic/threesixty/blob/master/dist/threesixty.min.js) just 3589 characters and the fiddle CDN file is 7539. I've copy pasted that code locally and works like a charm.

Finally, as you said in documentation, perRow and count are unnecessary working with images array.

Thanks a lot. Amazing library.

**Comment by mladenilic** [comment]
Hi @jonalxh, 

I'm glad you got it to work! The file you lined was a leftover from an older version and is deleted now.

I'll close the issue know, but if you encounter any other issue, feel free to re-open it.

Thanks!
