### ISSUE TITLE
How to import ThreeSixty to React component 

### ISSUE THREAD

**Issue by chingchinglcc** [mladenilic/threesixty#17]
Hello, I m trying to implement this library to my react project. I am wondering how can I import the library to my component? I tried to copy the codepen example on my component, but I got a ref error 
```
ReferenceError: ThreeSixty is not defined
```

I installed the library to my package.json

**Comment by mladenilic** [comment]
Hi @chingchinglcc, thanks for using threesixty.js.

Can you update your threesixty.js package version to `1.2.3`?  Then you can import it like an es6 module:
```
import ThreeSixty from '@mladenilic/threesixty.js';
```
