### ISSUE TITLE
scaling down larger images

### ISSUE THREAD

**Issue by sanwal123** [mladenilic/threesixty#2]
I have a sprite sheet in which every image is 328x328. Everything is working fine. But a further requirement is to load the same sprite with larger resolution so every 328x328 image in the new sprite is 2188x2188.
When I load this higher res sprite in a 328x328 div size it doesn't fit nor works correctly.
How would you scale down the larger sized sprites to smaller in your library.

By the way thank you for this awesome work I am really enjoying working on it.

**Comment by mladenilic** [comment]
Hi @sanwal123, glad you like it! Thanks for reaching out and opening an issue.

Can you please share some code, so I can recreate the issue. I'm not sure I completely understand the issue you are facing.

Best,
Mladen

**Comment by sanwal123** [comment]
Hey @mladenilic I just set the background-size property of the element to '800% auto' and it is working fine now.

Ok let me create a scenario
For example you have an image named as car.png and you write the following code to initiate the threesixty view

```
var threesixty = new ThreeSixty(document.getElementById('threesixty'), {
  image: 'car.png',
  count: 24,
  perRow: 8,
  width: 300,
  height:300
});
```

The above code works perfectly as long as every image in the `car.png`  sprite is of size 300x300.

Now total 24 images and 8 in each row means there are 3 rows and 8 columns in the sprite of `car.png` 

That means the image will have resolution of 2400x900  (2400 width and 900 height)

What if I was to load the same sprite `car.png` with every image as 900x900. Now the total resolution would be  7200x2700. The problem occurs if I write the same code above but don't change the `height` and `width` properties and let them stay 300 as defined above.

Now if we reload the page and try to rotate the image it wont work. Because the viewport size is 300x300 and every image that needs to show up is 900x900.

There should be a way to scale down sprite according to the defined width and height.

Right now after loading the above code I manually write the following code 

`document.getElementById('threesixty').style.backgroundSize='int% auto'` // int will the number that fits

and it fixes the problem perfectly. But I think there should be an option to do that with in the options param or the code should automatically do that for the user by using the following information
`sprite size, total count, images per row, width and height`  these are by default present in the library.

we just have to use it to decide the background size percentage which would be sweet or just give the user manual option in the options param to set the background size percentage.

I hope I have explained it enough. Please do ask me if you still have any question.

I have solved the issue manually but would love if the library did it by itself. I am working on the feature I just explained and If I am able to do it on the weekend then I would love to send you the update you can then update here or not.

Anyways thanks 😄

**Comment by mladenilic** [comment]
Ouuu, I think I see the issue.

I might find some time today to work on this, I'll let you know once I solve it. If you happen to solve it first, don't hesitate to open a PR. ;)

Thanks for the detailed explanation!

**Comment by mladenilic** [comment]
Hi @sanwal123,

Just letting you know that the I've added the background size property. Feel free to test it and let me know if it solves your problem.

Thanks again! 🎉

**Comment by sanwal123** [comment]
Hi @mladenilic Sorry I got really busy in work. I checked it and it works perfectly even for smaller images (sprites) with larger frame size defined. Thanks again cheers 😄
