### ISSUE TITLE
How to get the current index?

### ISSUE THREAD

**Issue by mindpixel-labs** [mladenilic/threesixty#6]
Are there any events or methods we can use to get the current index when dragging? I wanted to keep a range slider in sync based on when they drag the image.

A method like this to expose to the public API would probably work.

```
        self.getIndex = function () {
          return index;
        };
```

If you like I could submit a pull request. 

Thank you!

**Comment by mladenilic** [comment]
I agree. It makes perfect sense to expose index.

Feel free to open PR.

Thanks!
