### ISSUE TITLE
Responsive consideration?

### ISSUE THREAD

**Issue by markadrake** [mladenilic/threesixty#7]
Unless something has escaped me, the width/height value is required not only for defining the space on the screen but also in the calculation of background movement.

Could we also have an option to define a width-to-height ratio (1:1 for example) where the width of the element would be set to 100%, and the padding-bottom of the element would be set to an appropriate percentage? This would create a responsive and ratio-respecting space.

To transition for index to index, you could then use width percentages (100%, 200%, 300%, so on).

Not sure if anyone's thought to add this, tried it already, or would be interested in said feature. I may need to make the change however to support a client project. If I make it, I'll try to include a PR.

**Comment by jeanieherold** [comment]
@markadrake 
I made a responsive version of this using an array of images. It works really awesome. 
I probably did not do the pull request correctly. 
You can view the forked repo and see an example of the responsive in action on example2.html in the forked repo:
https://github.com/jeanieherold/threesixty
It has no conflicts with the master branch. 

@mladenilic - I tried to do another PR just now - let me know if you didnt get it ok.

**Comment by mladenilic** [comment]
@markadrake: Having an option to pass in the aspect ration sounds reasonable. If you get a chance to open PR, that'd be great. Thanks!

@jeanieherold: Sorry for not replying earlier to your PR. One of the things that we have to avoid is adding dependancies if not necessary. In your PR, you are using, what I assume is jQuery. I'd like to avoid that. Do you agree?

**Comment by thisanimus** [comment]
I needed the same, and ended up adding a little function that scales the viewer to the full width of the parent on window resize:

```
const viewer = document.getElementById('viewer');
const parent = viewer.parentNode;

const threesixty = new ThreeSixty(viewer, {
	image: 'assets/img/sprite.jpg',
	width: 1200,
	height: 600,
	count: 60,
	perRow: 6,
	speed: 100,
	prev: document.getElementById('left'),
	next: document.getElementById('right')
  });

function fullWidthScale(el, parent) {
	
	var scale = parent.clientWidth / el.offsetWidth;
	
	el.style.msTransform = 'scale(' + scale + ')';
	el.style.webkitTransform = 'scale(' + scale + ')';
	el.style.MozTransform = 'scale(' + scale + ')';
	el.style.OTransform = 'scale(' + scale + ')';
	el.style.transform = 'scale(' + scale + ')';
}

fullWidthScale(viewer, parent);

window.addEventListener('resize', function(e){
	fullWidthScale(viewer, parent);
});
```

**Comment by mladenilic** [comment]
@thisanimus: Thanks for the input.

@markadrake: Is there any progress on the PR?

**Comment by mladenilic** [comment]
@ilearnio added responsive support. I'll now add the documentation and the tests.

Thanks for the contributions 🎉
