### ISSUE TITLE
Listen for swipe gestures on a different element (instead of just the image itself).

### ISSUE THREAD

**Issue by markadrake** [mladenilic/threesixty#8]
Consider the following element on your web page:

![image](https://user-images.githubusercontent.com/713355/58511475-e0d2bd00-8168-11e9-87f9-e2d3c5ad02bf.png)

**By default:** The target area for gestures will match the width/height of the image only:

![image](https://user-images.githubusercontent.com/713355/58511542-065fc680-8169-11e9-8f96-219555124d84.png)

**Requested update:** I'd propose a new property in the config to allow override of the default behavior, so you can listen for and capture gestures on another element all together. This would allow a user to interact with the 360 view within a much greater area:

![image](https://user-images.githubusercontent.com/713355/58511612-2e4f2a00-8169-11e9-9b07-17cf1eb9cc4f.png)

I hope my suggestion is clear, please let me know if you'd like to see this as a PR. I have a project going on and may provide the perfect opportunity to make the change.

**Comment by mladenilic** [comment]
Hi @markadrake,

Sure, I'll merge such PR. 

With backward compatibility in mind, let's keep the new config property optional, defaulting to the current value. 

Thanks!

**Comment by markadrake** [comment]
Hi @mladenilic thanks so much for your response. I'll get started on that PR next week. Look forward to your feedback! All the best,

**Comment by mladenilic** [comment]
Hi @markadrake,

ThreeSixty now supports optional `swipeTarget` config option. All swipe/drag events will be registered on this element. If this option is omitted from config, then image container is used as swipe target.

Best!
