### ISSUE TITLE
Error: ThreeSixty is not a constructor

### ISSUE THREAD

**Issue by dwinnbrown** [mladenilic/threesixty#9]
I have currently implemented ThreeSixtyJS on my Wordpress site which was functioning without an issue here: http://dev.ridewithelka.co.uk/

However, I am now getting the following error: "ThreeSixty is not a constructor"

Could this be caused by a jQuery version dependency?

**Comment by mladenilic** [comment]
Hi @dwinnbrown, I took a quick look at the site you linked. It seems that there's another project with the same name.

I wasn't aware of this, but looking at threesixty.js that's loaded on your site, it's definitely a different one. :)

**Comment by dwinnbrown** [comment]
Ah I see thanks for the heads up.


Kind regards,

Dylan Winn-Brown
Founder and Project Manager
Winn-Brown & Co. Limited
3rd Floor 86-90 Paul Street, London, EC2A 4NE

T: 020 3488 3370
M: 07709126938
E: dylan@winn-brown.co.uk

Leave Notice: 10th August - 29th August
